---
name: "Bug"
description: "Report a bug found in the CLI"
title: "(short issue description)"
labels: [bug,needs-triage]
assignees: [mwwoda, mhagmajer, antusus, arjankowski, lukaszsocha2, bartlomiejleszczynski, congminh1254]
body:
body:
  - type: checkboxes
    id: sdk-docs-checked
    attributes:
      label: I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
      options:
        - label: Yes I've checked them.
          required: true
