---
name: "Bug"
description: "Report a bug found in the CLI"
title: "(short issue description)"
labels: [bug,needs-triage]
assignees: [mwwoda, mhagmajer, antusus, arjankowski, lukaszsocha2, bartlomiejleszczynski, congminh1254]
body:
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
