---
name: "Bug"
description: "Report a bug found in the CLI"
title: "(short issue description)"
labels: [bug,needs-triage]
assignees: [mwwoda, mhagmajer, antusus, arjankowski, lukaszsocha2, bartlomiejleszczynski, congminh1254]
body:
body:
  - type: checkboxes
    id: sdk-docs-checked
    attributes:
      label: I have checked that the SDK documentation doesn't solve my issue.
      description: <a href="/docs">SDK documentation</a> link
      options:
        - label: Yes I've checked them.
          required: true
  - type: checkboxes
    id: api-docs-checked
    attributes:
      label: I have checked that the API documentation doesn't solve my issue.
      description: <a href="https://developer.box.com/docs">API documentation</a> link
      options:
        - label: Yes I've checked them.
          required: true
  - type: checkboxes
    id: dev-forums-checked
    attributes:
      label: I have checked that the Box Developer Forums doesn't solve my issue.
      description: <a href="https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum">Box Developer Forums</a> link
      options:
        - label: Yes I've checked them.
          required: true
  - type: checkboxes
    id: github-repo-checked
    attributes:
      label: I have checked that the Box Developer Forums doesn't solve my issue.
      description: <a href="https://github.com/box/boxcli/search?type=Issues">Box Developer Forums</a> link
      options:
        - label: Yes I've checked them.
          required: true
  - type: input
    id: cli-version
    attributes:
      label: What is Box CLI Version used?
    validations:
      required: true
